### ISSUE TITLE
images not showing up on rarible

### ISSUE THREAD

**Issue by Quantmatic** [factoria-org/f0#1]
https://rinkeby.rarible.com/collection/0xd78D3D440848Bb451c6395b64bD2DE9789134f2A

https://testnet.factoria.app/f0/collection#address=0xd78D3D440848Bb451c6395b64bD2DE9789134f2A
<img width="1074" alt="Screenshot 2021-12-08 at 14 12 24" src="https://user-images.githubusercontent.com/27093143/145222978-f6f59d77-4400-410c-a2e4-1786cd34ac0b.png">
2A

**Comment by skogard** [comment]
Try refreshing the metadata. I don't know what exactly happened on Rarible end, but at least Opensea is displaying the images correctly https://testnets.opensea.io/assets/0xd78D3D440848Bb451c6395b64bD2DE9789134f2A/3

And refreshing metadata on Rarible worked too: https://rinkeby.rarible.com/token/0xd78D3D440848Bb451c6395b64bD2DE9789134f2A:3?tab=details

To learn how to refresh metadata on the marketplaces, see: https://docs.factoria.app/#/?id=_74-updating-nft-metadata-on-marketplaces

**Comment by Quantmatic** [comment]
Yes!


> And refreshing metadata on Rarible worked too: https://rinkeby.rarible.com/token/0xd78D3D440848Bb451c6395b64bD2DE9789134f2A:3?tab=details
